title: BloxyBay | Community Information Portal
description: A hub for all things BloxWorld
baseurl: "/"
url: ""

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Group":
    - "https://www.roblox.com/groups/14118208/BloxyBay#!/about"
  "Store":
    - "In Development"
  "Training Center":
    - "In Development"
  "Quiz Center":
    - "In Development"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs
